packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@effect/platform-node": 4.0.0-beta.99
  "@effect/sql-pg": 4.0.0-beta.99
  "@effect/tsgo": ^0.24.1
  "@effect/vitest": 4.0.0-beta.99
  "@types/node": ^24
  "@types/pg": ^8.20.0
  alchemy: 2.0.0-beta.63
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  effect: 4.0.0-beta.99
  pg: ^8.22.0
  typescript: 7.1.0-dev.20260715.1
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

minimumReleaseAgeExclude:
  - "@distilled.cloud/aws@0.29.1"
  - "@distilled.cloud/axiom@0.29.1"
  - "@distilled.cloud/cloudflare@0.29.1"
  - "@distilled.cloud/core@0.29.1"
  - "@distilled.cloud/neon@0.29.1"
  - "@distilled.cloud/planetscale@0.29.1"
  - alchemy@2.0.0-beta.63

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  workerd: true
