import * as Dialog from "@foldkit/ui/dialog"
import {
  PolicyEditorState,
  PublishState,
  RepositoryState,
  RowMutationState,
  RuleDeleteState,
  RuleEditorState,
  TestState,
  ValidationState,
  type Model,
} from "./model"

export const init = (): Model => ({
  tab: "Policies",
  repository: RepositoryState.cases.NoRepository.make({}),
  repositoryRequest: null,
  refreshError: null,
  statusMessage: null,
  nextRequestId: 1,
  nextNodeSequence: 1,
  policyEditor: PolicyEditorState.cases.PolicyEditorClosed.make({}),
  validation: ValidationState.cases.ValidationIdle.make({}),
  publishing: PublishState.cases.PublishClosed.make({}),
  ruleEditor: RuleEditorState.cases.RuleEditorClosed.make({}),
  ruleDeletion: RuleDeleteState.cases.RuleDeleteClosed.make({}),
  test: TestState.cases.TestClosed.make({}),
  rowMutation: RowMutationState.cases.RowMutationIdle.make({}),
  policyEditorDialog: Dialog.init({ id: "policy-editor" }),
  publishDialog: Dialog.init({ id: "publish-policy" }),
  ruleEditorDialog: Dialog.init({ id: "rule-editor" }),
  ruleDeleteDialog: Dialog.init({ id: "delete-rule" }),
  testDialog: Dialog.init({ id: "policy-test" }),
  policyMenus: {},
  ruleMenus: {},
})
